export { default as Footer } from './Footer/Footer';
export { default as Header} from './Header/Header';
export { default as HeroSection } from './HeroSection/HeroSection';
export { default as AnimateText } from './AnimateText/AnimateText';
export { default as Technologies } from './Technologies/Technologies';
export { default as Projects} from './Projects/Projects';
export { default as Experience } from './Experience/Experience';
export { default as MobileMenuButton } from './MobileMenu/MobileMenuButton';
export { default as FaviconStatus } from './FaviconStatus/FaviconStatus';
export { default as VerificationBlock } from './VerificationBlock/VerificationBlock';